version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always

volumes:
  backend_data: